on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, closed ]

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    name: Comment PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:
