on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, closed ]

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    name: Comment PR
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout previous version
        uses: actions/checkout@v3
        with:
          repository: cesarParra/expression
          ref: 'v2.2.0'
          path: previous

      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install ApexDocs globally
        run: npm install @cparra/apexdocs --global

      - name: Generate changelog
        run: apexdocs changelog --currentVersionDir expression-src --previousVersionDir './previous/force-app' --targetDir changelog

      - name: Read Changelog contents
        id: changelog
        uses: jaywcjlove/github-action-read-file@main
        with:
          path: changelog/changelog.md

      - name: Echo package.json
        run: echo "${{ steps.changelog.outputs.content }}"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.changelog.outputs.content }}
